### ISSUE TITLE
Figure out treatment for activity number indicator

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#4]
@chadsansing can you weigh in on these... 

![image](https://cloud.githubusercontent.com/assets/25212/18593329/c8c30142-7bef-11e6-8f09-584de40cdc9d.png)

Appears on - https://mozilla.github.io/curriculum-final/color-picker-challenge/#overview
- Will the read / write / participate thing be on every activity?
- Is it always going to indicate which of the 3 the activty tackles?
- The 2 of X part - should it be there for this activity?
  - Is this activity a part of a set or collection or something? Should we indicate that?
  - Makes sense to have links to the previous and next activity, yeah?

Cheers.

**Comment by chadsansing** [comment]
@flukeout - this should be "Activity 1 of 1," or we can delete the line since this is a standalone activity.

Generally, a forward / backward nav element would be great here, as well, except for standalone a ctivities.

We will keep using Read / Write / Participate until we decide not to - worth discussing as we build the database - is this useful to anyone but us in how we think of activities? I think that so long as it's part of the Web Lit Map, we use it.
